"""Heading-aware Markdown chunking strategy."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from .base import (
    ChunkDraft,
    DocumentMetadata,
    Tokenizer,
    build_embedding_text,
)

HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")
LIST_ITEM_RE = re.compile(r"^(?:[-+*]|\d+[.)])\s+")
SENTENCE_RE = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9`*\[])")
TABLE_SEPARATOR_RE = re.compile(
    r"^\s*\|?\s*:?-{3,}:?\s*(?:\|\s*:?-{3,}:?\s*)+\|?\s*$"
)


@dataclass
class Section:
    """One heading and its directly owned content and child sections."""

    level: int
    title: str | None = None
    heading: str | None = None
    blocks: list[str] = field(default_factory=list)
    children: list["Section"] = field(default_factory=list)


class HierarchicalChunkingStrategy:
    """Keep Markdown section subtrees intact until they exceed the limit."""

    name = "hierarchical"

    def chunk(
        self,
        document: str,
        metadata: DocumentMetadata,
        tokenizer: Tokenizer,
        max_tokens: int,
        overlap_tokens: int,
    ) -> list[ChunkDraft]:
        if max_tokens <= 0:
            raise ValueError("max_tokens must be greater than zero")
        if overlap_tokens < 0:
            raise ValueError("overlap_tokens cannot be negative")
        if overlap_tokens >= max_tokens:
            raise ValueError("overlap_tokens must be smaller than max_tokens")

        root = parse_markdown_sections(document)
        drafts: list[ChunkDraft] = []
        self._emit_section(
            root,
            (),
            metadata,
            tokenizer,
            max_tokens,
            overlap_tokens,
            drafts,
        )
        return drafts

    def _emit_section(
        self,
        section: Section,
        parent_path: tuple[str, ...],
        metadata: DocumentMetadata,
        tokenizer: Tokenizer,
        max_tokens: int,
        overlap_tokens: int,
        drafts: list[ChunkDraft],
    ) -> None:
        path = _section_path(section, parent_path, metadata.title)
        subtree = _render_subtree(section)
        if subtree and _fits(subtree, path, metadata, tokenizer, max_tokens):
            drafts.append(ChunkDraft(subtree, path))
            return

        own_content = _render_own_content(section)
        if own_content:
            drafts.extend(
                _split_oversized_content(
                    own_content,
                    path,
                    metadata,
                    tokenizer,
                    max_tokens,
                    overlap_tokens,
                )
            )

        for child in section.children:
            self._emit_section(
                child,
                path,
                metadata,
                tokenizer,
                max_tokens,
                overlap_tokens,
                drafts,
            )


def strip_front_matter(document: str) -> str:
    """Remove the simple YAML front matter generated by ingestion."""

    lines = document.splitlines()
    if not lines or lines[0].strip() != "---":
        return document.strip()
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return "\n".join(lines[index + 1 :]).strip()
    raise ValueError("Markdown front matter is missing its closing delimiter")


def parse_markdown_sections(document: str) -> Section:
    """Parse Markdown headings into a tree while respecting fenced code."""

    root = Section(level=0)
    stack = [root]
    pending: list[str] = []
    fence_marker: str | None = None

    def flush() -> None:
        block = "\n".join(pending).strip()
        if block:
            stack[-1].blocks.extend(_semantic_blocks(block))
        pending.clear()

    for line in strip_front_matter(document).splitlines():
        fence_match = FENCE_RE.match(line)
        if fence_marker is not None:
            pending.append(line)
            if fence_match and fence_match.group(1).startswith(fence_marker[0]) and len(
                fence_match.group(1)
            ) >= len(fence_marker):
                fence_marker = None
            continue
        if fence_match:
            fence_marker = fence_match.group(1)
            pending.append(line)
            continue

        heading_match = HEADING_RE.match(line)
        if not heading_match:
            pending.append(line)
            continue

        flush()
        level = len(heading_match.group(1))
        title = _plain_heading(heading_match.group(2))
        while stack[-1].level >= level:
            stack.pop()
        section = Section(level=level, title=title, heading=line.strip())
        stack[-1].children.append(section)
        stack.append(section)

    flush()
    return root


def _semantic_blocks(markdown: str) -> list[str]:
    """Split on blank lines without splitting fenced code blocks."""

    blocks: list[str] = []
    current: list[str] = []
    fence_marker: str | None = None
    for line in markdown.splitlines():
        fence_match = FENCE_RE.match(line)
        if fence_match:
            marker = fence_match.group(1)
            if fence_marker is None:
                fence_marker = marker
            elif marker.startswith(fence_marker[0]) and len(marker) >= len(fence_marker):
                fence_marker = None
            current.append(line)
        elif not line.strip() and fence_marker is None:
            if current:
                blocks.append("\n".join(current).strip())
                current.clear()
        else:
            current.append(line)
    if current:
        blocks.append("\n".join(current).strip())
    return blocks


def _section_path(
    section: Section,
    parent_path: tuple[str, ...],
    document_title: str,
) -> tuple[str, ...]:
    if section.title is None:
        return parent_path
    if section.level == 1 and not parent_path and _same_heading(
        section.title, document_title
    ):
        return parent_path
    return parent_path + (section.title,)


def _same_heading(left: str, right: str) -> bool:
    normalize = lambda value: re.sub(r"\W+", " ", value).strip().casefold()
    return normalize(left) == normalize(right)


def _plain_heading(markdown: str) -> str:
    value = re.sub(r"\[([^]]+)]\([^)]+\)", r"\1", markdown)
    return re.sub(r"[*_`~]", "", value).strip()


def _render_own_content(section: Section) -> str:
    parts: list[str] = []
    if section.heading:
        parts.append(section.heading)
    parts.extend(section.blocks)
    return "\n\n".join(parts).strip()


def _render_subtree(section: Section) -> str:
    parts = [_render_own_content(section)]
    parts.extend(_render_subtree(child) for child in section.children)
    return "\n\n".join(part for part in parts if part).strip()


def _fits(
    content: str,
    path: tuple[str, ...],
    metadata: DocumentMetadata,
    tokenizer: Tokenizer,
    max_tokens: int,
) -> bool:
    return (
        tokenizer.count(build_embedding_text(metadata.title, path, content))
        <= max_tokens
    )


def _split_oversized_content(
    content: str,
    path: tuple[str, ...],
    metadata: DocumentMetadata,
    tokenizer: Tokenizer,
    max_tokens: int,
    overlap_tokens: int,
) -> list[ChunkDraft]:
    units: list[str] = []
    for block in _semantic_blocks(content):
        units.extend(
            _make_fitting_units(block, path, metadata, tokenizer, max_tokens)
        )

    chunks: list[ChunkDraft] = []
    current: list[str] = []
    for unit in units:
        candidate = "\n\n".join(current + [unit])
        if current and not _fits(
            candidate, path, metadata, tokenizer, max_tokens
        ):
            chunks.append(ChunkDraft("\n\n".join(current), path))
            current = _overlap_suffix(current, tokenizer, overlap_tokens)
            while current and not _fits(
                "\n\n".join(current + [unit]),
                path,
                metadata,
                tokenizer,
                max_tokens,
            ):
                current.pop(0)
        current.append(unit)
    if current:
        chunks.append(ChunkDraft("\n\n".join(current), path))
    return chunks


def _make_fitting_units(
    block: str,
    path: tuple[str, ...],
    metadata: DocumentMetadata,
    tokenizer: Tokenizer,
    max_tokens: int,
) -> list[str]:
    if _fits(block, path, metadata, tokenizer, max_tokens):
        return [block]

    candidates = _split_list(block) or _split_table(block) or _split_sentences(block)
    if len(candidates) > 1:
        units: list[str] = []
        for candidate in candidates:
            units.extend(
                _make_fitting_units(
                    candidate, path, metadata, tokenizer, max_tokens
                )
            )
        return units

    return _hard_split_block(
        block, path, metadata, tokenizer, max_tokens
    )


def _hard_split_block(
    block: str,
    path: tuple[str, ...],
    metadata: DocumentMetadata,
    tokenizer: Tokenizer,
    max_tokens: int,
) -> list[str]:
    """Token-split one atomic block and verify the final prefixed size."""

    opening = ""
    closing = ""
    payload = block
    lines = block.splitlines()
    if len(lines) >= 2 and FENCE_RE.match(lines[0]) and FENCE_RE.match(lines[-1]):
        opening = lines[0]
        closing = lines[-1]
        payload = "\n".join(lines[1:-1])

    prefix_tokens = tokenizer.count(
        build_embedding_text(metadata.title, path, "")
    )
    piece_budget = max_tokens - prefix_tokens - 2
    while piece_budget > 0:
        pieces = tokenizer.split(payload, piece_budget)
        if opening:
            pieces = [f"{opening}\n{piece}\n{closing}" for piece in pieces]
        if pieces and all(
            _fits(piece, path, metadata, tokenizer, max_tokens)
            for piece in pieces
        ):
            return pieces
        piece_budget -= max(1, piece_budget // 10)

    raise ValueError("Title and heading context leave no room for document content")


def _split_list(block: str) -> list[str]:
    lines = block.splitlines()
    starts = [index for index, line in enumerate(lines) if LIST_ITEM_RE.match(line)]
    if len(starts) < 2:
        return []
    units: list[str] = []
    if starts[0] > 0:
        units.append("\n".join(lines[: starts[0]]).strip())
    for index, start in enumerate(starts):
        end = starts[index + 1] if index + 1 < len(starts) else len(lines)
        units.append("\n".join(lines[start:end]).strip())
    return [unit for unit in units if unit]


def _split_table(block: str) -> list[str]:
    lines = block.splitlines()
    if len(lines) < 4 or not TABLE_SEPARATOR_RE.match(lines[1]):
        return []
    header = "\n".join(lines[:2])
    return [f"{header}\n{row}" for row in lines[2:] if row.strip()]


def _split_sentences(block: str) -> list[str]:
    sentences = [part.strip() for part in SENTENCE_RE.split(block) if part.strip()]
    return sentences if len(sentences) > 1 else []


def _overlap_suffix(
    units: list[str], tokenizer: Tokenizer, overlap_tokens: int
) -> list[str]:
    if overlap_tokens == 0:
        return []
    suffix: list[str] = []
    for unit in reversed(units):
        candidate = [unit] + suffix
        if tokenizer.count("\n\n".join(candidate)) > overlap_tokens:
            break
        suffix = candidate
    return suffix
