"""Heading-aware Markdown chunking strategy."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from .base import (
    ChunkDraft,
    DocumentMetadata,
    Tokenizer,
    build_embedding_text,
)

HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")
LIST_ITEM_RE = re.compile(r"^(?:[-+*]|\d+[.)])\s+")
SENTENCE_RE = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9`*\[])")
TABLE_SEPARATOR_RE = re.compile(
    r"^\s*\|?\s*:?-{3,}:?\s*(?:\|\s*:?-{3,}:?\s*)+\|?\s*$"
)


@dataclass
class TextSpan:
    """Text plus its start and end character offsets in the original document."""

    text: str
    start: int
    end: int

    @property
    def span(self) -> tuple[int, int]:
        """Return start and end offsets as a tuple."""

        return (self.start, self.end)


@dataclass
class Section:
    """One heading and its directly owned content and child sections."""

    level: int
    title: str | None = None
    heading: str | None = None
    heading_span: tuple[int, int] | None = None
    blocks: list[TextSpan] = field(default_factory=list)
    children: list["Section"] = field(default_factory=list)


class HierarchicalChunkingStrategy:
    """Keep Markdown section subtrees intact until they exceed the limit."""

    name = "hierarchical"

    def chunk(
        self,
        document: str,
        metadata: DocumentMetadata,
        tokenizer: Tokenizer,
        max_tokens: int,
        overlap_tokens: int,
    ) -> list[ChunkDraft]:
        if max_tokens <= 0:
            raise ValueError("max_tokens must be greater than zero")
        if overlap_tokens < 0:
            raise ValueError("overlap_tokens cannot be negative")
        if overlap_tokens >= max_tokens:
            raise ValueError("overlap_tokens must be smaller than max_tokens")

        root = parse_markdown_sections(document)
        drafts: list[ChunkDraft] = []
        self._emit_section(
            root,
            (),
            metadata,
            tokenizer,
            max_tokens,
            overlap_tokens,
            drafts,
        )
        return drafts

    def _emit_section(
        self,
        section: Section,
        parent_path: tuple[str, ...],
        metadata: DocumentMetadata,
        tokenizer: Tokenizer,
        max_tokens: int,
        overlap_tokens: int,
        drafts: list[ChunkDraft],
    ) -> None:
        path = _section_path(section, parent_path, metadata.title)
        subtree = _render_subtree(section)
        if subtree and _fits(subtree.text, path, metadata, tokenizer, max_tokens):
            drafts.append(ChunkDraft(subtree.text, path, subtree.span))
            return

        own_parts = _render_own_parts(section)
        own_content = _join_text_spans(own_parts)
        if own_content:
            drafts.extend(
                _split_oversized_content(
                    own_parts,
                    path,
                    metadata,
                    tokenizer,
                    max_tokens,
                    overlap_tokens,
                )
            )

        for child in section.children:
            self._emit_section(
                child,
                path,
                metadata,
                tokenizer,
                max_tokens,
                overlap_tokens,
                drafts,
            )


def strip_front_matter(document: str) -> str:
    """Remove the simple YAML front matter generated by ingestion."""

    return _document_body(document)[0]


def _document_body(document: str) -> tuple[str, int]:
    """Return document content after front matter with its original start offset."""

    lines = document.splitlines()
    if not lines or lines[0].strip() != "---":
        leading = len(document) - len(document.lstrip())
        return document.strip(), leading

    offset = 0
    for index, line in enumerate(document.splitlines(keepends=True)):
        offset += len(line)
        if index > 0 and line.strip() == "---":
            raw_body = document[offset:]
            leading = len(raw_body) - len(raw_body.lstrip())
            return raw_body.strip(), offset + leading
    raise ValueError("Markdown front matter is missing its closing delimiter")


def parse_markdown_sections(document: str) -> Section:
    """Parse Markdown headings into a tree while respecting fenced code."""

    body, body_offset = _document_body(document)
    root = Section(level=0)
    stack = [root]
    pending: list[TextSpan] = []
    fence_marker: str | None = None

    def flush() -> None:
        if pending:
            stack[-1].blocks.extend(_semantic_blocks_from_lines(pending))
        pending.clear()

    for line_span in _iter_line_spans(body, body_offset):
        line = line_span.text
        fence_match = FENCE_RE.match(line)
        if fence_marker is not None:
            pending.append(line_span)
            if fence_match and fence_match.group(1).startswith(fence_marker[0]) and len(
                fence_match.group(1)
            ) >= len(fence_marker):
                fence_marker = None
            continue
        if fence_match:
            fence_marker = fence_match.group(1)
            pending.append(line_span)
            continue

        heading_match = HEADING_RE.match(line)
        if not heading_match:
            pending.append(line_span)
            continue

        flush()
        level = len(heading_match.group(1))
        title = _plain_heading(heading_match.group(2))
        while stack[-1].level >= level:
            stack.pop()
        heading = line.strip()
        heading_start = line_span.start + len(line) - len(line.lstrip())
        section = Section(
            level=level,
            title=title,
            heading=heading,
            heading_span=(heading_start, heading_start + len(heading)),
        )
        stack[-1].children.append(section)
        stack.append(section)

    flush()
    return root


def _semantic_blocks(markdown: str) -> list[str]:
    """Split on blank lines without splitting fenced code blocks."""

    blocks: list[str] = []
    current: list[str] = []
    fence_marker: str | None = None
    for line in markdown.splitlines():
        fence_match = FENCE_RE.match(line)
        if fence_match:
            marker = fence_match.group(1)
            if fence_marker is None:
                fence_marker = marker
            elif marker.startswith(fence_marker[0]) and len(marker) >= len(fence_marker):
                fence_marker = None
            current.append(line)
        elif not line.strip() and fence_marker is None:
            if current:
                blocks.append("\n".join(current).strip())
                current.clear()
        else:
            current.append(line)
    if current:
        blocks.append("\n".join(current).strip())
    return blocks


def _iter_line_spans(document: str, offset: int) -> list[TextSpan]:
    """Return document lines without newline characters and with absolute spans."""

    spans: list[TextSpan] = []
    cursor = offset
    for raw_line in document.splitlines(keepends=True):
        line = raw_line.rstrip("\r\n")
        spans.append(TextSpan(line, cursor, cursor + len(line)))
        cursor += len(raw_line)
    if document and not document.endswith(("\n", "\r")):
        return spans
    return spans


def _semantic_blocks_from_lines(lines: list[TextSpan]) -> list[TextSpan]:
    """Split line spans on blank lines without splitting fenced code blocks."""

    blocks: list[TextSpan] = []
    current: list[TextSpan] = []
    fence_marker: str | None = None
    for line_span in lines:
        fence_match = FENCE_RE.match(line_span.text)
        if fence_match:
            marker = fence_match.group(1)
            if fence_marker is None:
                fence_marker = marker
            elif marker.startswith(fence_marker[0]) and len(marker) >= len(fence_marker):
                fence_marker = None
            current.append(line_span)
        elif not line_span.text.strip() and fence_marker is None:
            if current:
                blocks.append(_trim_line_span_block(current))
                current.clear()
        else:
            current.append(line_span)
    if current:
        blocks.append(_trim_line_span_block(current))
    return blocks


def _trim_line_span_block(lines: list[TextSpan]) -> TextSpan:
    """Render a line span block and trim its outer whitespace from the span."""

    first = next(line for line in lines if line.text.strip())
    last = next(line for line in reversed(lines) if line.text.strip())
    start = first.start + len(first.text) - len(first.text.lstrip())
    end = last.end - (len(last.text) - len(last.text.rstrip()))
    text = "\n".join(line.text for line in lines).strip()
    return TextSpan(text, start, end)


def _section_path(
    section: Section,
    parent_path: tuple[str, ...],
    document_title: str,
) -> tuple[str, ...]:
    if section.title is None:
        return parent_path
    if section.level == 1 and not parent_path and _same_heading(
        section.title, document_title
    ):
        return parent_path
    return parent_path + (section.title,)


def _same_heading(left: str, right: str) -> bool:
    normalize = lambda value: re.sub(r"\W+", " ", value).strip().casefold()
    return normalize(left) == normalize(right)


def _plain_heading(markdown: str) -> str:
    value = re.sub(r"\[([^]]+)]\([^)]+\)", r"\1", markdown)
    return re.sub(r"[*_`~]", "", value).strip()


def _render_own_content(section: Section) -> TextSpan | None:
    return _join_text_spans(_render_own_parts(section))


def _render_own_parts(section: Section) -> list[TextSpan]:
    """Return the heading and directly owned content blocks for a section."""

    parts: list[TextSpan] = []
    if section.heading and section.heading_span:
        parts.append(TextSpan(section.heading, *section.heading_span))
    parts.extend(section.blocks)
    return parts


def _render_subtree(section: Section) -> TextSpan | None:
    parts = [_render_own_content(section)]
    parts.extend(_render_subtree(child) for child in section.children)
    return _join_text_spans([part for part in parts if part])


def _join_text_spans(parts: list[TextSpan]) -> TextSpan | None:
    """Join text spans with chunk separators and keep their covering span."""

    if not parts:
        return None
    text = "\n\n".join(part.text for part in parts if part.text).strip()
    return TextSpan(text, parts[0].start, parts[-1].end)


def _fits(
    content: str,
    path: tuple[str, ...],
    metadata: DocumentMetadata,
    tokenizer: Tokenizer,
    max_tokens: int,
) -> bool:
    return (
        tokenizer.count(build_embedding_text(metadata.title, path, content))
        <= max_tokens
    )


def _split_oversized_content(
    content: list[TextSpan],
    path: tuple[str, ...],
    metadata: DocumentMetadata,
    tokenizer: Tokenizer,
    max_tokens: int,
    overlap_tokens: int,
) -> list[ChunkDraft]:
    units: list[TextSpan] = []
    for block in content:
        units.extend(
            _make_fitting_units(block, path, metadata, tokenizer, max_tokens)
        )

    chunks: list[ChunkDraft] = []
    current: list[TextSpan] = []
    for unit in units:
        candidate = _join_text_spans(current + [unit])
        if current and not _fits(
            candidate.text, path, metadata, tokenizer, max_tokens
        ):
            chunk = _join_text_spans(current)
            chunks.append(ChunkDraft(chunk.text, path, chunk.span))
            current = _overlap_suffix(current, tokenizer, overlap_tokens)
            while current and not _fits(
                _join_text_spans(current + [unit]).text,
                path,
                metadata,
                tokenizer,
                max_tokens,
            ):
                current.pop(0)
        current.append(unit)
    if current:
        chunk = _join_text_spans(current)
        chunks.append(ChunkDraft(chunk.text, path, chunk.span))
    return chunks


def _make_fitting_units(
    block: TextSpan,
    path: tuple[str, ...],
    metadata: DocumentMetadata,
    tokenizer: Tokenizer,
    max_tokens: int,
) -> list[TextSpan]:
    if _fits(block.text, path, metadata, tokenizer, max_tokens):
        return [block]

    candidates = _split_list(block) or _split_table(block) or _split_sentences(block)
    if len(candidates) > 1:
        units: list[TextSpan] = []
        for candidate in candidates:
            units.extend(
                _make_fitting_units(
                    candidate, path, metadata, tokenizer, max_tokens
                )
            )
        return units

    return _hard_split_block(
        block, path, metadata, tokenizer, max_tokens
    )


def _hard_split_block(
    block: TextSpan,
    path: tuple[str, ...],
    metadata: DocumentMetadata,
    tokenizer: Tokenizer,
    max_tokens: int,
) -> list[TextSpan]:
    """Token-split one atomic block and verify the final prefixed size."""

    opening = ""
    closing = ""
    payload = block.text
    lines = block.text.splitlines()
    if len(lines) >= 2 and FENCE_RE.match(lines[0]) and FENCE_RE.match(lines[-1]):
        opening = lines[0]
        closing = lines[-1]
        payload = "\n".join(lines[1:-1])

    prefix_tokens = tokenizer.count(
        build_embedding_text(metadata.title, path, "")
    )
    piece_budget = max_tokens - prefix_tokens - 2
    while piece_budget > 0:
        pieces = tokenizer.split(payload, piece_budget)
        if opening:
            pieces = [f"{opening}\n{piece}\n{closing}" for piece in pieces]
        if pieces and all(
            _fits(piece, path, metadata, tokenizer, max_tokens)
            for piece in pieces
        ):
            return _locate_text_spans(block, pieces)
        piece_budget -= max(1, piece_budget // 10)

    raise ValueError("Title and heading context leave no room for document content")


def _split_list(block: TextSpan) -> list[TextSpan]:
    lines = block.text.splitlines()
    starts = [index for index, line in enumerate(lines) if LIST_ITEM_RE.match(line)]
    if len(starts) < 2:
        return []
    units: list[str] = []
    if starts[0] > 0:
        units.append("\n".join(lines[: starts[0]]).strip())
    for index, start in enumerate(starts):
        end = starts[index + 1] if index + 1 < len(starts) else len(lines)
        units.append("\n".join(lines[start:end]).strip())
    return _locate_text_spans(block, [unit for unit in units if unit])


def _split_table(block: TextSpan) -> list[TextSpan]:
    lines = block.text.splitlines()
    if len(lines) < 4 or not TABLE_SEPARATOR_RE.match(lines[1]):
        return []
    header = "\n".join(lines[:2])
    return _locate_text_spans(
        block,
        [f"{header}\n{row}" for row in lines[2:] if row.strip()],
    )


def _split_sentences(block: TextSpan) -> list[TextSpan]:
    sentences = [part.strip() for part in SENTENCE_RE.split(block.text) if part.strip()]
    return _locate_text_spans(block, sentences) if len(sentences) > 1 else []


def _locate_text_spans(source: TextSpan, pieces: list[str]) -> list[TextSpan]:
    """Locate split pieces inside a source span."""

    spans: list[TextSpan] = []
    cursor = 0
    for piece in pieces:
        start = source.text.find(piece, cursor)
        if start == -1:
            start = source.text.find(piece)
        if start == -1:
            spans.append(TextSpan(piece, source.start, source.end))
            continue
        end = start + len(piece)
        spans.append(TextSpan(piece, source.start + start, source.start + end))
        cursor = end
    return spans


def _overlap_suffix(
    units: list[TextSpan], tokenizer: Tokenizer, overlap_tokens: int
) -> list[TextSpan]:
    if overlap_tokens == 0:
        return []
    suffix: list[TextSpan] = []
    for unit in reversed(units):
        candidate = [unit] + suffix
        text = _join_text_spans(candidate)
        if text and tokenizer.count(text.text) > overlap_tokens:
            break
        suffix = candidate
    return suffix
